development:
  adapter: postgresql
  encoding: unicode
  database: php8_development
  pool: 5
  username: postgres
  password: 123456
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: php8_development
  pool: 5
  username: postgres
  password: 123456
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: php8_test
  pool: 5
  username: postgres
  password: 123456
  timeout: 5000
